dist: trusty
sudo: false
language: java
before_install:
  - ulimit -c unlimited -S
  - 'wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh'
script:
  - ./mvnw test -B -P code-coverage
  - ./mvnw site -pl docs -B
after_success:
  - bash .travis_after_success.sh
cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - os: linux
      env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10
deploy:
  provider: script
  script: bash .travis_deploy.sh
  on:
    repo: dropwizard/dropwizard
    branch: master
    jdk: oraclejdk8
# encrypted CI_DEPLOY_USERNAME and CI_DEPLOY_PASSWORD
# values for maven deploy. these have been encrypted
# with the public key from https://github.com/dropwizard/dropwizard
# and won't work in any other repository. if you want
# to run CI in your local fork you'll need to run `travis encrypt ...`
# accordingly (http://docs.travis-ci.com/user/encryption-keys/)
#
# NOTE: CI_DEPLOY_USERNAME is set to dropwizardci, the username
# we've set up with Sonatype, which only has permission to push
# to the snapshot repo.
env:
  global:
    - secure: "EAuz7bCKj4r438IEC2y73WVrFwXirflbXA4HhpwVmAFWNqC9LIIpkWcO5GVp773HsZvJBcJjJriP+aKRkImV8AyMgjCeEUv2dlezvbkIIz38vKyw9MWaPIyZ3uS9RCuL7OwGf5BeJ1DvHFYdMBaspZd+EmCYr7abnHdqs+Tm/W8="
    - secure: "RI0QcuKMsij3sgRm+Bjhu3X217U6UslvSzcRv13iLLwrTj73zhGi5PF/+kj8Qh1HMQw0oQRR6M8qPqGy82KcjiGbpgPgSy1rVAvkYg+Yw1k7v4l7Vgyj7TNsAM3pqHyojx2jgRjpQsgw/WXQmiahWV6OCOUzdbhEUwVzIXI+vtk="
    - JAVA_OPTS: "'-Xms512m -Xmx2g'"
