dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk13
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
script:
  - ./mvnw verify -B
  - ./mvnw site -pl docs -B -q
after_success:
  - bash ci/after_success.sh
cache:
  directories:
    - $HOME/.m2
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ci/deploy-snapshot.sh
    on:
      repo: dropwizard/dropwizard
      tags: false
      branch: master
      jdk: openjdk8
  - provider: script
    skip_cleanup: true
    script: bash ci/deploy-release.sh
    on:
      repo: dropwizard/dropwizard
      tags: true
      jdk: openjdk8
# encrypted CI_DEPLOY_USERNAME and CI_DEPLOY_PASSWORD
# values for maven deploy. these have been encrypted
# with the public key from https://github.com/dropwizard/dropwizard
# and won't work in any other repository. if you want
# to run CI in your local fork you'll need to run `travis encrypt ...`
# accordingly (http://docs.travis-ci.com/user/encryption-keys/)
env:
  global:
    - JAVA_OPTS: "'-Xms512m -Xmx2g'"
    - secure: "MPnKTiK+9rmqu4R1f2Wozj/DuC8M74THepmvXZKCB6ysCkXPjf7FuWxd29uVdk3Mwb4X90KdzyafOY/GVkVze+/AEorFjIF8FFqBpgGmOG5D9PMKZbF7DNisOShPsITz6+RmYzRTT5xLeRGntAAy6aDWtWTh06CSCypEMT5lD10="
    - secure: "WY1zEZD8nwGQXaYDrItkBWmYHhbQ3Ekseq82cTIJedG7zb8KbwpVDUo+6yRf1EPmpnDbRE9N0wgtzQq8B3+X87ZnO6RrEuv6ulkLJJlrwcRmRjfDY9rwRTUUbFZYrHP0fiLedPE6xpokPiO7Y+tRpofVfv2YnxW69GWwQG224KY="
    - secure: "W4rGYMaNKW2K1oSJFEr1Q+InQxvW4cdXk6Z1wE+U3CeZd8YeZ8RaaRUVObTMeeUvIzYlbU/stb9dghQMyYKjgaOZE3zWzDV9NP1e83sX7LyCd3q9wufEzI2dwenfXDnVHehG110wXWjUQSAwYyUTXn5bzMvyHSCqwN4X5mGSFzw="
    - secure: "Oi1Ni7GZUEY0AqFDkWqKrsX7p1OVoPgYVcM//edlst0QUE1rRVzrQAaucJYATis+K9l+/00fIC4OlqXv2pk+wufMCKi+rFeDqHBvYMz8vwYE2MBbcuT8FEoeIJUA9SeOj/RtNQZw7ynOqhfu1f0x8XMPazA7W2/i8CEMuoa/+Rk="
