language: java

install: echo "I trust Maven."

# don't just run the tests, also run Findbugs and friends
script: mvn verify

jdk:
  - oraclejdk7

notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - coda.hale@gmail.com
