---
# yamllint disable rule:comments
name: "Qodana"
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - 'release/*'

jobs:
  qodana:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
      checks: "write"
      security-events: "write"
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        # yamllint disable-line rule:line-length
        uses: JetBrains/qodana-action@a4f50a611a0bbd9f4bf505cf7ab577611d2d07ca # v2024.1.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      # yamllint disable-line rule:line-length
      - uses: github/codeql-action/upload-sarif@d39d31e687223d841ef683f52467bd88e9b21c14 # v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
